'use client'

import { motion } from 'framer-motion'
import { useState } from 'react'

export default function Projects() {
  const [filter, setFilter] = useState('All')
  
  const projects = [
    {
      id: 1,
      title: 'WorkOut Mate',
      description: '일회성 운동 메이트 연결 서비스 플랫폼 서버 API',
      tags: ['Java', 'Spring Boot', 'WebSocket', 'Docker'],
      category: 'Web',
      featured: true,
    },
    {
      id: 2,
      title: 'Tags Generated By Ai With Crawler',
      description: '크롤링한 글에 n8n을 활용하여 Ai가 태그를 판단하는 자동화 프로그램',
      tags: ['n8n', 'JavaScript'],
      category: 'Web',
      featured: true,
    },
    {
      id: 3,
      title: 'Ebbi Adventure',
      description: '일정 개수 이상의 아이템을 수집하여 클리어하는 구조의 2D 아케이드 게임',
      tags: ['Unity', 'C#'],
      category: 'Mobile',
      featured: false,
    },
  ]

  const categories = ['All', 'Web', 'Mobile']
  
  const filteredProjects = filter === 'All' 
    ? projects 
    : projects.filter(p => p.category === filter)

  return (
    <section id="projects" className="py-32 px-6">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-5xl md:text-7xl font-display font-bold mb-4">
            <span className="text-gradient">My Work</span>
          </h2>
          <p className="text-xl text-[var(--text-secondary)]">
            Featured Projects
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="flex justify-center gap-4 mb-12 flex-wrap"
        >
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setFilter(category)}
              className={`px-6 py-3 rounded-full font-display font-semibold transition-all ${
                filter === category
                  ? 'bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)] text-white'
                  : 'bg-[var(--bg-secondary)] text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
            >
              {category}
            </button>
          ))}
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8">
          {filteredProjects.map((project, index) => (
            <motion.div
              key={project.id}
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              whileHover={{ y: -10 }}
              className={`bg-[var(--bg-secondary)] rounded-3xl overflow-hidden card-glow hover:shadow-[0_0_60px_rgba(77,159,255,0.3)] transition-all ${
                project.featured ? 'md:col-span-2' : ''
              }`}
            >
              <div className="p-8">
                {project.featured && (
                  <span className="inline-block px-4 py-2 bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)] rounded-full text-sm font-semibold mb-4">
                    Featured
                  </span>
                )}
                
                <h3 className="text-3xl font-display font-bold mb-4">
                  {project.title}
                </h3>
                
                <p className="text-[var(--text-secondary)] text-lg mb-6 leading-relaxed">
                  {project.description}
                </p>
                
                <div className="flex flex-wrap gap-3 mb-6">
                  {project.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-4 py-2 bg-[var(--bg-primary)] rounded-full text-sm font-medium"
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                <div className="flex gap-4">
                  <a
                    href="#"
                    className="flex items-center gap-2 text-[var(--accent-primary)] hover:text-[var(--accent-secondary)] transition-colors font-semibold"
                  >
                    View Project →
                  </a>
                  <a
                    href="https://github.com/earhart123/ebbi_advanture_2d"
                    className="flex items-center gap-2 text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                  >
                    GitHub →
                  </a>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center mt-16"
        >
          <a
            href="https://github.com/earhart123"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-8 py-4 bg-[var(--bg-secondary)] rounded-full font-display font-semibold hover:shadow-[0_0_40px_rgba(255,77,166,0.3)] transition-all"
          >
            View More on GitHub →
          </a>
        </motion.div>
      </div>
    </section>
  )
}
